Fix/bottom safe area
okwasniewski/react-native-bottom-tabs pull request #37
Opened 2024-10-11 10:35 UTC by okwasniewski

This PR fixes bottom safe area handling by measuring the tab bar on the native side and offsetting it in JS.

https://github.com/user-attachments/assets/5973256f-26b9-46aa-94a8-2c420a468517

2024-10-11 10:35 UTC, okwasniewski commented
cc @dylancom let me know what you think 👍🏻

2024-10-11 11:12 UTC, dylancom commented
Will look into more details later. Does this work with "overflow: visible" on a scrollview/flatlist? In the video it seems that the content isn't blurred below the tabbar.

2024-10-11 13:58 UTC, dylancom commented
In order to make the blurring backgorund on the tabbar work `overflow: visible` needs to be set on the scrollviews.
A bit a shame that this is working out of the box when switching to UIKit.

<img src="https://github.com/user-attachments/assets/c5deae07-7bae-493c-af5e-9ce596c90f4d" alt="Simulator Screenshot - iPhone 16 Pro - 2024-10-11 at 15 51 05" width="300">

2024-10-11 18:10 UTC, dylancom requested changes

2024-10-11 18:10 UTC, dylancom commented on TabMeasuredEvent.swift
File should be moved to ios/ folder. Currently getting an error that TabMeasuredEvent can't be found.

2024-10-12 07:30 UTC, okwasniewski commented
Hey @dylancom I finally figured it out!! 

Now its working with the built-in behavior 🚀


https://github.com/user-attachments/assets/76082f3a-e0c9-4e2e-b8f9-4f14f395c099

2024-10-12 16:51 UTC, dylancom commented
Clever find!!
Awesome.

2024-10-13 11:48 UTC, dylancom commented
Some bugs while testing on my end. The scrollbar starts too late in the top and on reaching the end some content is still below the tabbar.

<img src="https://github.com/user-attachments/assets/7d51cce1-ee4a-4a51-a00a-1430a64645f1" width="300" />
<img src="https://github.com/user-attachments/assets/d438d044-e156-4e3e-8302-ca99a2ec41cf" width="300" />

2024-10-14 18:24 UTC, merged

2024-10-14 19:19 UTC, dylancom commented
If I test the example app in the latest main the content still ends below the tabbar on my end.

2024-10-14 21:01 UTC, ferrannp commented
@okwasniewski I just tried this and the issue still persists. Do you have a working example?

2024-11-03 12:31 UTC, jnsdrssn commented
@ferrannp try `contentInsetAdjustmentBehavior="always"` on the `ScrollView`